server:
  port: 3001

management:
  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  secret: YourStrongSecretKey
  expirationMs: 3600000  # 1 hour in milliseconds

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drone_monitor?createDatabaseIfNotExist=true
    username: root
    password: Savindulike2020.
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update





